# Generated by Django 3.2.5 on 2021-08-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
