# Generated by Django 3.2.5 on 2021-08-26 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='timeline',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.timeline'),
        ),
    ]
