# Generated by Django 3.2.5 on 2021-08-26 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210826_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='text',
        ),
    ]
