# Generated by Django 3.2.5 on 2021-10-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='mex', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
