# Generated by Django 3.2.5 on 2021-10-24 23:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_token_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='token',
            name='expires',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
