# Generated by Django 3.2.5 on 2021-10-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_token_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='username',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
    ]
